# Generated by Django 2.1.5 on 2019-03-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='youtube_link_video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
