# Generated by Django 2.1.5 on 2019-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_youtube_link_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='text',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='youtube_link_video',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
